### ISSUE TITLE
Can this not be done without iphone?

### ISSUE THREAD

**Issue by noobs-creation** [pkhungurn/talking-head-anime-3-demo#18]

**Comment by pkhungurn** [comment]
Sorry for the long silence. The answer is yes and no.

Yes, because you can modify the code to accept pose inputs from sources other than iFacialMocap. In fact, other users have modified it so that it can be used with MeowFace, for example: https://gitlab.com/pale_color/talking-head-anime-3-with-switchable-images.

No, because, as far as this repository goes, no support for pose sources other than iFacialMocap will be added unless I have the motivation to do so.
